spring:
  datasource:
    dynamic:
      enabled: false
      primary: master
      strict: false
      datasource:
        master:
          pool-name: act-pool-master
          type: com.linkcircle.ss.LHikariDataSource
          url: jdbc:mysql://172.16.252.55:3300/act_pro?characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
          username: root
          #password: R4GPOT1iiI7Q4rjdL14MAuYkrdYbHld3lqoEA62V3/Yjg0Il9XIJGHwVQO6dUr4Bt2n4n2FX0iWf981sCiz9QA==
          password: R4GPOT1iiI7Q4rjdL14MAuYkrdYbHld3lqoEA62V3/Yjg0Il9XIJGHwVQO6dUr4Bt2n4n2FX0iWf981sCiz9QA==
          driverClassName: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 900000
        connection-test-query: 'select 1'
        validation-timeout: 1000
        max-pool-size: 30
        min-idle: 1
  shardingsphere:
    rules:
      sharding:
        tables:
          trace_label:
            actualDataNodes: sharding-datasource.trace_label*
            tableStrategy:
              complex:
                shardingColumns: tenand_id,create_time
                shardingAlgorithmName: trace_label-complex
        shardingAlgorithms:
          trace_label-complex:
            type: CLASS_BASED
            props:
              strategy: COMPLEX
              algorithmClassName: com.yyl.sharding.TraceLabelComplexKeysShardingAlgorithm
    props:
      show-sql: true


mysql:
  url:
    format: jdbc:mysql://%s:%s/%s?characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
mybatis-plus:
  mapper-locations: mapper/*.xml

